
bids_dir: /project/6007967/akhanf/ext-bids/hcpUR100_3T/bids
prepdwi_dir: /project/6007967/akhanf/ext-bids/hcpUR100_3T/deriv/1_fakeprepdwi



#segmentations in subject native space:
seed_seg_dir: /project/6007967/sudesnac/HCP/data
seed_seg_nii: sub-{subject}/{hemi}_full{seed}50_sub-{subject}_bin.nii.gz
excroi_nii: sub-{subject}/{excroi}_sub-{subject}.nii.gz
ufile_nii: sub-{subject}/u_rc1msub-{subject}_acq-procHCP_T1w_HCP3TUR100_template.nii

#segmentation in template space for defining groupwise masks (should be same structure as seeds)


template: hcpdartel
template_seg_dir: /project/6007967/sudesnac/HCP/BF_ROIs/Zaborszky_2020_thresholded/HCPDARTELwarpped
template_seg_nii: HCP_{hemi}_full{seed}_seed_temp.nii.gz

seeds:
 - BF
hemis:
 - B
excrois:
 - AC
 - BrStem

#targets in subject native space
targets_txt: cfg/hcpmmp_rois.txt
targets_lut_in: cfg/hcpmmp_input.lut
targets_lut_out: cfg/hcpmmp_output.lut
targets_seg_dir: /project/6007967/sudesnac/HCP/diffparc_BF/work/
targets_seg_bilat: sub-{subject}/labels/t1/HCPNATIVE/HCP-MMP1.nii.gz


#fsl 6.0.1, ants; also:  mri_convert (from freesurfer) reg_resample (niftyreg) 
singularity_neuroglia: /project/6007967/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif 

#contains mrtrix 3.0RC3
singularity_prepdwi: /project/6007967/akhanf/singularity/bids-apps/khanlab_prepdwi_latest.sif

#singularity_neuroglia: docker://khanlab/neuroglia-core:latest  

max_k: 12

#tractography parameters
probtrack:
    seed_resolution: 1.25
    nsamples: 5000
    opts: '--loopcheck --onewaycondition --cthr=0.2 --nsteps=2000 --steplength=0.5  --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd --os2t --randfib=2' 


enable_dropbox: False
dropbox_token: ADD_LATER



